1. values added: 20
2. final result: 20
3. values added: 20
4. This returns an error, since result is declared using let the scope only lies within the if statement.
5. This returns an error, since result is a const, and can not be reassigned after it was assigned the value 0.
6. Though line 13 wont be executed due to the error on line 9, it would throw an error, since result is attempted to be accessed outside of scope.
   